### ISSUE TITLE
[Bug]: Latest CE dev build xml errors

### ISSUE THREAD

**Issue by Taranchuk** [CombatExtended-Continued/CombatExtended#2122]
Rimworld version: 1.4 latest stable
Combat Extended version: 1.4 from steam
Combat Extended source (Steam, GitHub, etc.): steam
Your operating system: windows 10
Your mod list: 

**Description**
Upon startup I'm getting following errors
[Combat Extended - Start of stack trace]
Verse.PatchOperationAdd(xpath="Defs/HediffDef[defName="Trunken_hediff_IndependentEye"]/stages/li"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_CombatAdvancedBionics.xml
 
[Combat Extended - Start of stack trace]
Verse.PatchOperationReplace(xpath="Defs/HediffDef[defName="Trunken_hediff_Zoom"]/stages/li/statOffsets/ShootingAccuracyPawn"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_CombatBionics.xml
 
[Combat Extended - Start of stack trace]
Verse.PatchOperationReplace(xpath="Defs/HediffDef[defName="Trunken_hediff_BerserkerChip"]/stages/li/statOffsets/MeleeHitChance"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_MindAlteringBionics.xml
 
[Combat Extended - Start of stack trace]
Verse.PatchOperationAdd(xpath="Defs/HediffDef[defName="Trunken_hediff_BlackPearl"]"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_ProductiveBionics.xml
 
[Combat Extended] Patch operation Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_CombatAdvancedBionics.xml 

[Combat Extended] Patch operation Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_CombatBionics.xml 

[Combat Extended] Patch operation Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_MindAlteringBionics.xml 

[Combat Extended] Patch operation Verse.PatchOperationFindMod(Cybernetic Organism and Neural Network) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Cybernetic Organism and Neural Network\Hediffs\CONN_ProductiveBionics.xml 

[Combat Extended] Patch operation Verse.PatchOperationFindMod([Fuu] Uncompromising Tribal Faction) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Uncompromising Tribal Faction\PawnKindDefs_Neolithic.xml 

**Expected behavior**
Simply to not have these errors upon startup.
**To reproduce**
Just launch the game with Cybernetic Organism and Neural Network mod.
https://steamcommunity.com/sharedfiles/filedetails/?id=2045064990
**Screenshots & log dumps**
https://gist.github.com/fac93a42f00266907d7f95c76c0a3042

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
The patch for the mod is already updated in the dev build of CE, could you please try with the dev snapshot of CE and see if the errors persist or not?

**Comment by Taranchuk** [comment]
Looks it was fixed in the dev build, however I'm getting another error due to Apparel_Backpack not being found
Could not resolve cross-reference to Verse.ThingDef named Apparel_Backpack (wanter=apparelRequired)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.ThingDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.ThingDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

Failed to find Verse.ThingDef named Apparel_Backpack. There are 12447 defs of this type loaded.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.DefDatabase`1<Verse.ThingDef>:GetNamed (string,bool)
(wrapper dynamic-method) Verse.GenDefDatabase:Verse.GenDefDatabase.GetDef_Patch1 (System.Type,string,bool)
RimWorld.DefOfHelper:BindDefsFor (System.Type)
System.Threading.Tasks.Parallel/<>c__DisplayClass31_0`2<System.Type, object>:<ForEachWorker>b__0 (int)
System.Threading.Tasks.Parallel/<>c__DisplayClass17_0`1<object>:<ForWorker>b__1 ()
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:InnerInvokeWithArg (System.Threading.Tasks.Task)
System.Threading.Tasks.Task/<>c__DisplayClass178_0:<ExecuteSelfReplicating>b__0 (object)
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by SamaelGray** [comment]
`Apparel_Backpack` is renamed to `CE_Apparel_Backpack`, it's still not updated in mods like Caravan Adventures and Hospitality.

**Comment by Taranchuk** [comment]
Okay, great. Looks like installing CE is still a big headache to attempt to do it.
