### ISSUE TITLE
[Bug]: Cannons from Not Only Just A Cannon can't deal direct damage to armored targets

### ISSUE THREAD

**Issue by randomtyper** [CombatExtended-Continued/CombatExtended#598]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: Cannons from Not Only Just A Cannon can't deal direct damage to armored targets

**Specifications**
Please provide the following.

Rimworld version: 1.2.2900 (64-bit)
Combat Extended version: 1.2.3.2 (version that already has revolver balance changes, so less than 7 days old)
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 10
Your mod list: 
Harmony
Core
Mod Manager
Combat Extended
Not Only Just A Cannon
Turret Collection (control mod)

**Description**
Cannons from Not Only Just A Cannon (both chamber-loaded and standard) cannot penetrate armoured enemies with solid rounds despite having listed penetration of 100 mm RHA.

**Expected behavior**
Penetration and damaging of the armored targets bodyparts (for example, centipedes) with the main shell body, not the secondary fragments/explosion.

**To reproduce**
1. Create a new colony. 
2. Place some pillboxes with cannon and turret emplacements, and place ammo inside. 
3. Man turrets and cannons with colonists with shooting skill of 20. 
4. Spawn in a centipede so that it is in the turrets' range and arcs of fire. 
5. Try to attack with cannons from NOJAC mod using solid ammo. 
6. Fail to penetrate miserably. 
7. Use a CE 90 mm cannon or turrets from Turret Collection with armor-piercing ammo. 
8. Shred the centipede to pieces.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

Results of Not Only Just A Cannon cannons salvo (two cannon types (3 pivot and 2 fortress), solid "high-explosive anti-tank" ammo)
Log (first 4 messages from top)
![изображение](https://user-images.githubusercontent.com/59539398/114085399-0038e600-98ba-11eb-801a-8b0e1822483a.png)
Results (only a shattered sensor? are you serious?)
![изображение](https://user-images.githubusercontent.com/59539398/114085555-32e2de80-98ba-11eb-8a3f-16dfdec2b2e7.png)

Results of heavy machine gun turret burst from Turret Collection (.50 bmg sabots)
![изображение](https://user-images.githubusercontent.com/59539398/114085138-a20c0300-98b9-11eb-9070-b6bf88e3921d.png)

Results of Avenger turret burst from Turret Collection (30 mm FMJ)
![изображение](https://user-images.githubusercontent.com/59539398/114084985-71c46480-98b9-11eb-8c2f-35e2cd56f4d7.png)

Results of heavy machine gun turret burst from Turret Collection (.50 bmg FMJ) + Oerlikon turret HE ammo burst
![изображение](https://user-images.githubusercontent.com/59539398/114082650-a97ddd00-98b6-11eb-8243-8d5e3d92c6b0.png)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
This isn't related to Not Only Cannons itself, but is another matter addressed by #610

**Comment by randomtyper** [comment]
> This isn't related to Not Only Cannons itself, but is another matter addressed by #610

The thing is that the issue is not about sensors soaking damage. It is about inability of cannons to penetrate their targets. Other turrets do well while turrets from Not Only Just A Cannon cannot do the same.

**Comment by randomtyper** [comment]
I ask you to reopen the issue, because the bug persisted even after applying the changes from #610.
